# Generated by Django 5.2.5 on 2025-12-07 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catType', models.IntegerField(choices=[(1, 'Residential'), (2, 'Commercial'), (3, 'Land'), (4, 'Other')], default=1, help_text='Select category type.', verbose_name='Category Type')),
                ('cat_name', models.CharField(help_text='Enter Category Name.', max_length=64, verbose_name='Category Name')),
                ('cat_slug', models.SlugField(help_text='Enter Category Slug.', max_length=225, unique=True, verbose_name='Category Slug')),
                ('meta_title', models.CharField(blank=True, help_text='Enter Category Meta Title (optional).', max_length=85, verbose_name='Category Title')),
                ('meta_desc', models.TextField(blank=True, help_text='Enter Category Meta Description (optional).', max_length=165, verbose_name='Category Description')),
                ('meta_keyword', models.CharField(blank=True, help_text='Enter Category Meta Keywords (optional).', max_length=255, null=True, verbose_name='Category Keyword')),
                ('status', models.BooleanField(default=True, help_text='Designates whether this category should be treated as active.')),
                ('linkable', models.BooleanField(default=True, help_text='Whether this category should be shown as a link.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('cat_name',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(help_text='Enter Sub Category Name.', max_length=32, verbose_name='Sub Category Name')),
                ('cat_slug', models.SlugField(help_text='Enter Sub Category Slug.', max_length=32, unique=True, verbose_name='Sub Category Slug')),
                ('meta_title', models.CharField(blank=True, help_text='Enter Sub Category Meta Title (optional).', max_length=85, verbose_name='Sub Category Title')),
                ('meta_desc', models.TextField(blank=True, help_text='Enter Sub Category Meta Description (optional).', max_length=165, verbose_name='Sub Category Description')),
                ('meta_keyword', models.CharField(blank=True, help_text='Enter Sub Category Meta Keywords (optional).', max_length=255, null=True, verbose_name='Sub Category Keyword')),
                ('status', models.BooleanField(default=True, help_text='Designates whether this subcategory should be treated as active.')),
                ('linkable', models.BooleanField(default=True, help_text='Whether this subcategory should be shown as a link.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Select parent Category.', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='category.category')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'ordering': ('cat_name',),
            },
        ),
        migrations.CreateModel(
            name='SubChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(default=None, help_text='Type: Int, Values: Enter Name', max_length=32, verbose_name='Sub Child Category Name')),
                ('cat_slug', models.SlugField(default=None, help_text='Type: Int, Values: Enter Slug', max_length=32, unique=True, verbose_name='Sub Child Category Slug')),
                ('meta_title', models.CharField(default=None, help_text='Type: Int, Values: Enter Meta Title', max_length=85, verbose_name='Sub Category Title')),
                ('meta_desc', models.TextField(default=None, help_text='Type: String, Values: Enter Meta Description.', max_length=165, verbose_name='Category Description')),
                ('meta_keyword', models.CharField(blank=True, help_text='Type: String, Values: Enter Meta Keywords.', max_length=255, null=True, verbose_name='Category Keyword')),
                ('status', models.BooleanField()),
                ('linkable', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(default=None, help_text='Type: Int, Values: Select Sub Category', on_delete=django.db.models.deletion.CASCADE, related_name='subchild', to='category.subcategory', verbose_name='Select Sub Category')),
            ],
        ),
    ]
