# Generated by Django 5.2.5 on 2026-04-07 17:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subchildcategory',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Enter the main page content for this subcategory landing page.', null=True, verbose_name='Page Content'),
        ),
        migrations.AlterField(
            model_name='subchildcategory',
            name='meta_desc',
            field=models.TextField(blank=True, help_text='Type: String, Values: Enter Meta Description.', max_length=165, null=True, verbose_name='Category Description'),
        ),
        migrations.AlterField(
            model_name='subchildcategory',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Type: Int, Values: Enter Meta Title', max_length=85, null=True, verbose_name='Sub Category Title'),
        ),
    ]
