# Generated by Django 6.0 on 2025-12-28 05:23

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=32)),
                ('slug', models.SlugField(default=None, max_length=32)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('meta_desc', models.CharField(blank=True, max_length=120, null=True)),
                ('keyword', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('slug', models.SlugField(max_length=225, unique=True)),
                ('meta_title', models.CharField(max_length=225)),
                ('meta_desc', models.TextField(max_length=285)),
                ('keyword', models.CharField(blank=True, max_length=164, null=True)),
                ('overview', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Type: string, Default: null, Values: Project Overview.', null=True, verbose_name='Project Overview')),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blog_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(default=None, related_name='BlogCategoryPost', to='blog.blogcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_thumb', models.ImageField(blank=True, null=True, upload_to='')),
                ('main_thumb_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('large_thumb', models.ImageField(blank=True, null=True, upload_to='')),
                ('large_thumb_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blogId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogimgs', to='blog.blog')),
            ],
        ),
    ]
