# Generated by Django 5.2.5 on 2025-12-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='Blog/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='BlogImages',
        ),
    ]
