# Generated by Django 5.2.5 on 2025-12-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='security_deposit',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category_wise_city',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pr_status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_cat_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sTags',
        ),
    ]
