# Generated by Django 5.2.5 on 2026-03-29 14:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_education_health_transportation'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='detail',
            name='bank_loan_availability',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Loan Availability'),
        ),
        migrations.AddField(
            model_name='detail',
            name='construction_permission',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Construction Permission'),
        ),
        migrations.AddField(
            model_name='detail',
            name='distance_to_airport',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Distance to Airport'),
        ),
        migrations.AddField(
            model_name='detail',
            name='distance_to_delhi',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Distance to Delhi'),
        ),
        migrations.AddField(
            model_name='detail',
            name='distance_to_railway',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Distance to Railway'),
        ),
        migrations.AddField(
            model_name='detail',
            name='eligibility',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Eligibility'),
        ),
        migrations.AddField(
            model_name='detail',
            name='gst_on_plot',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='GST on Plot'),
        ),
        migrations.AddField(
            model_name='detail',
            name='internal_road_width',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Internal Road Width'),
        ),
        migrations.AddField(
            model_name='detail',
            name='main_road_width',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Main Road Width'),
        ),
        migrations.AddField(
            model_name='detail',
            name='metro_expansion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Metro Expansion'),
        ),
        migrations.AddField(
            model_name='detail',
            name='nearby_university',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nearby University'),
        ),
        migrations.AddField(
            model_name='detail',
            name='project_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='detail',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='detail',
            name='registry_type',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Registry Type'),
        ),
        migrations.AddField(
            model_name='detail',
            name='rrts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RRTS'),
        ),
        migrations.AddField(
            model_name='detail',
            name='scheme',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Scheme'),
        ),
        migrations.AlterField(
            model_name='project',
            name='keyfeatures',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Type: string, Default: null, Values: Project Education & Healthcare Hub.', null=True, verbose_name='Education/Healthcare Hub'),
        ),
    ]
