# Generated by Django 5.2.5 on 2026-03-31 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_detail_approved_by_detail_bank_loan_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('source', models.CharField(choices=[('enquire', 'Enquire Now'), ('brochure', 'Download Brochure'), ('get_quote', 'Get Quote'), ('website', 'Website')], default='website', max_length=32, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='project.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Lead',
                'verbose_name_plural': 'Project Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
