# Generated by Django 5.2.5 on 2026-04-07 17:30

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_subchildcategory_content_and_more'),
        ('project', '0005_projectlead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. Plots for Sale in Sonipat', max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(help_text='URL slug, e.g. plots-for-sale-in-sonipat', max_length=255, unique=True, verbose_name='Slug')),
                ('meta_title', models.CharField(blank=True, max_length=165, null=True, verbose_name='Meta Title')),
                ('meta_desc', models.TextField(blank=True, max_length=255, null=True, verbose_name='Meta Description')),
                ('meta_keyword', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Rich-text content displayed on this landing page above the project listings.', null=True, verbose_name='Page Content')),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subchild_category', models.ForeignKey(help_text='The subchild category this link page belongs to (determines the first URL segment).', on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='category.subchildcategory', verbose_name='Subchild Category')),
            ],
            options={
                'verbose_name': 'Project Link',
                'verbose_name_plural': 'Project Links',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.ForeignKey(blank=True, help_text='Select the Project Links landing page this project is listed under.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='project.projectlinks', verbose_name='Project Link Page'),
        ),
    ]
